### ISSUE TITLE
Pipeline support

### ISSUE THREAD

**Issue by ryanslade** [Leonidas-from-XIV/orewa#1]
Thanks, this looks awesome.

Pipeline support would be greatly appreciated as this is lacking from the other redis binding I've used (https://github.com/0xffea/ocaml-redis)

I thought it would be good to mention it as it might require a bit of refactoring to make it work for all commands.

**Comment by Leonidas-from-XIV** [comment]
Hi @ryanslade. I agree that pipelining would be useful. I had some discussions about it and it should not be *too hard* to add but I need to think how to do that best (and also how to test that it is indeed working).
